<<<<<<< HEAD
﻿auto: true
markdown: rdiscount
pygments: true
paginate:         6
permalink:        /:title

title:            freestyle21
url:              http://freestyle21.github.com
feed:             /atom.xml
author:
    name:         freestyle21
description:      "freestyle21\'s Blog"
author_info:      <a href="http://freestyle21.github.com">freestyle21</a>

copyright:
    - Design by <a href="http://freestyle21.github.com/about" title="freestyle21" target="_blank">freestyle21</a> &copy; 2013
=======
auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         6
permalink:        /:title

title:            BeiYuu.com
url:              http://beiyuu.com
feed:             /atom.xml
author:
    name:         BeiYuu
    twitter:      twitter.com/beiyuu
description:      "BeiYuu\'s Blog"
author_info:      <a href="http://beiyuu.com/about">BeiYuu</a>

copyright:
    - Design by <a href="http://beiyuu.com/about" title="BeiYuu" target="_blank">BeiYuu</a> &copy; 2013
>>>>>>> fd462b0464901c1325eabeafe1cc92736ae108e0
